#!/bin/bash

python3 scoreboard/scoreboard.py scoreboard/training-camp-argentina-2024/scoreboard.csv scoreboard/training-camp-argentina-2024 scoreboard/Config
python3 ranking/ranking.py ranking/training-camp-argentina-2024/registered.csv ranking/training-camp-argentina-2024 ranking/Config